{% set name = "backports-datetime-fromisoformat" %}
{% set version = "2.0.3" %}


package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  #url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | lower }}-{{ version }}.tar.gz
  url: https://github.com/movermeyer/backports.datetime_fromisoformat/archive/refs/tags/v{{ version}}.tar.gz
  sha256: a0db0e99bdc33f7ebce1b73e19fca613f964b50d627bc69d11e90750dbdfe068

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - backports
    - backports.datetime_fromisoformat
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/movermeyer/backports.datetime_fromisoformat
  summary: Backport of Python 3.7's datetime.fromisoformat
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
